<?php
$z[0]=Array("arclist","\r\n				<div class=\"select_left\">\r\n					<h2>[field:title/]</h2>\r\n					<p>[field:description function=\"cn_substr(@me,450)\"/]...</p>\r\n					<span>\r\n						[field:shorttitle/]\r\n					</span>\r\n				</div>\r\n				",3907,4178);
$z[0][4]=array();
$z[0][4]['typeid']="5";
$z[0][4]['row']="3";
$z[1]=Array("arclist","\r\n					<li><img src=\"img/images/583542234849392254.png\"> \r\n						<p>[field:description function=\"cn_substr(@me,20)\"/]...</p>\r\n					</li>\r\n					",5472,5686);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['typeid']="6";

?>